export default function useLista1() {
    const algo = ([
        { name: 'Despreocupado', id: 0, isClicked: false },
        { name: 'Calmo', id: 1, isClicked: true },
        { name: 'Animado', id: 2, isClicked: true },
        { name: 'Jovial', id: 3, isClicked: true },
        { name: 'Sociável', id: 4, isClicked: true },
        { name: 'Simpático', id: 5, isClicked: true },
        { name: 'Loquaz', id: 6, isClicked: true },
        { name: 'Age Rápido', id: 7, isClicked: true },
        { name: 'Workaholic', id: 8, isClicked: true },
        { name: 'Tagarela', id: 9, isClicked: true },
        { name: 'Eloqüente', id: 10, isClicked: true },
        { name: 'Superficial', id: 11, isClicked: true },
        { name: 'Expansivo', id: 12, isClicked: true },
        { name: 'Falante', id: 13, isClicked: true },
        { name: 'Amigável', id: 14, isClicked: true },
        { name: 'Adaptável', id: 15, isClicked: true },
        { name: 'Pitoresco', id: 16, isClicked: true },
        { name: 'Brilhante', id: 17, isClicked: true },
        { name: 'Impaciente', id: 18, isClicked: true },
        { name: 'Irresponsável', id: 19, isClicked: true },
        { name: 'Não-Confiável', id: 20, isClicked: true },
        { name: 'Fugido', id: 21, isClicked: true },
        { name: 'Flexível', id: 22, isClicked: true },
        { name: 'Generoso', id: 23, isClicked: true },
        { name: 'Levanta Cedo', id: 24, isClicked: true },
        { name: 'Volúvel', id: 25, isClicked: true },
        { name: 'Feliz', id: 26, isClicked: true },
    ]);
    const algo2 = ([
        { name: 'Impulsivo', id: 0, isClicked: false },
        { name: 'Irrequieto', id: 1, isClicked: true },
        { name: 'Esquentado', id: 2, isClicked: true },
        { name: 'Ativo', id: 3, isClicked: true },
        { name: 'Excitável', id: 4, isClicked: true },
        { name: 'Corado', id: 5, isClicked: true },
        { name: 'Agressivo', id: 6, isClicked: true },
        { name: 'Um Líder', id: 7, isClicked: true },
        { name: 'Convincente', id: 8, isClicked: true },
        { name: 'Cheio de Energia', id: 9, isClicked: true },
        { name: 'Extrovertido', id: 10, isClicked: true },
        { name: 'Turbulento', id: 11, isClicked: true },
        { name: 'Impaciente', id: 12, isClicked: true },
        { name: 'Empreendedor', id: 13, isClicked: true },
        { name: 'Pioneiro', id: 14, isClicked: true },
        { name: 'Barulhento', id: 15, isClicked: true },
        { name: 'Prático', id: 16, isClicked: true },
        { name: 'Dramático', id: 17, isClicked: true },
        { name: 'Esquecido', id: 18, isClicked: true },
        { name: 'Esportivo', id: 19, isClicked: true },
        { name: 'Competitivo', id: 20, isClicked: true },
        { name: 'Resistente', id: 21, isClicked: true },
        { name: 'Dominador', id: 22, isClicked: true },
        { name: 'Intolerante', id: 23, isClicked: true },
        { name: 'Obstinado', id: 24, isClicked: true },
        { name: 'Irascível', id: 25, isClicked: true },
        { name: 'Audaz', id: 26, isClicked: true },
    ]);

    const algo3 = ([
        { name: 'Pessimista', id: 0, isClicked: false },
        { name: 'Melancólico', id: 1, isClicked: true },
        { name: 'Amuado', id: 2, isClicked: true },
        { name: 'Sóbrio', id: 3, isClicked: true },
        { name: 'Nervoso', id: 4, isClicked: true },
        { name: 'Distante', id: 5, isClicked: true },
        { name: 'Quieto', id: 6, isClicked: true },
        { name: 'Reservado', id: 7, isClicked: true },
        { name: 'Resignado', id: 8, isClicked: true },
        { name: 'Triste', id: 9, isClicked: true },
        { name: 'Desanimado', id: 10, isClicked: true },
        { name: 'Pensativo', id: 11, isClicked: true },
        { name: 'Introspectivo', id: 12, isClicked: true },
        { name: 'Egoísta', id: 13, isClicked: true },
        { name: 'Exigente', id: 14, isClicked: true },
        { name: 'Suscetível', id: 15, isClicked: true },
        { name: 'Leitor', id: 16, isClicked: true },
        { name: 'Lento', id: 17, isClicked: true },
        { name: 'Tristonho', id: 18, isClicked: true },
        { name: 'Taciturno', id: 19, isClicked: true },
        { name: 'Intelectual', id: 20, isClicked: true },
        { name: 'Boa Memória', id: 21, isClicked: true },
        { name: 'Observador', id: 22, isClicked: true },
        { name: 'Ingrato', id: 23, isClicked: true },
        { name: 'Insatisfeito', id: 24, isClicked: true },
        { name: 'Abnegado', id: 25, isClicked: true },
        { name: 'Inconsolável', id: 26, isClicked: true },

    ]);
    const algo4 = ([
        { name: 'Cuidadoso', id: 0, isClicked: false },
        { name: 'Metódico', id: 1, isClicked: true },
        { name: 'Estável', id: 2, isClicked: true },
        { name: 'Passivo', id: 3, isClicked: true },
        { name: 'Pacato', id: 4, isClicked: true },
        { name: 'Pensativo', id: 5, isClicked: true },
        { name: 'Calmo', id: 6, isClicked: true },
        { name: 'Controlado', id: 7, isClicked: true },
        { name: 'Folgado', id: 8, isClicked: true },
        { name: 'Plácido', id: 9, isClicked: true },
        { name: 'Sem Pressa', id: 10, isClicked: true },
        { name: 'Lento', id: 11, isClicked: true },
        { name: 'Implacável', id: 12, isClicked: true },
        { name: 'Comedido', id: 13, isClicked: true },
        { name: 'Tranqüilo', id: 14, isClicked: true },
        { name: 'Ensimesmado', id: 15, isClicked: true },
        { name: 'Reservado', id: 16, isClicked: true },
        { name: 'Sonhador', id: 17, isClicked: true },
        { name: 'Gosta de Rotina', id: 18, isClicked: true },
        { name: 'Lento para Aprender', id: 19, isClicked: true },
        { name: 'Perseverante', id: 20, isClicked: true },
        { name: 'Obstinado', id: 21, isClicked: true },
        { name: 'Tímido', id: 22, isClicked: true },
        { name: 'Constante', id: 23, isClicked: true },
        { name: 'Sensato', id: 24, isClicked: true },
        { name: 'Indiferente', id: 25, isClicked: true },
        { name: 'Apático', id: 26, isClicked: true },
    ]);
    return {
        retornaAlgo: algo,
        retor: algo2,
        retorn: algo3,
        retorno: algo4
    }
};