export default function useLista2() {
    const lista1 = ([
        "Que não se preocupa; que não se interessa por nada; sem preocupações; tranquilo.",
        "Que está em estado de calma; sem agitação; sossegado, sereno, pacato.",
        "Dotado de vida: um ser animado.",
        "Que tem jovialidade; alegre, expansivo: espírito jovial.",
        "Que tem facilidade em conviver em sociedade; comunicativo.",
        "Que revela simpatia; agradável, atraente.",
        "Que fala muito; tagarela.",
        "Que age de maneira rápida; age com rapidez.",
        "Pessoa viciada em trabalho; alguém que trabalha excessivamente.",
        "Que fala muito; loquaz.",
        "Que se expressa de maneira persuasiva e convincente.",
        "Que se limita à superfície; que não vai a fundo; frívolo.",
        "Que se expande; que revela expansão de ânimo; comunicativo.",
        "Que fala muito; loquaz.",
        "Que é propenso a fazer amizades; simpático.",
        "Que se adapta facilmente; maleável.",
        "Que tem caráter pintoresco; peculiar.",
        "Que brilha; que se destaca; luminoso.",
        "Que não tem paciência; ansioso.",
        "Que não assume responsabilidades; negligente.",
        "Que não é digno de confiança; pouco confiável.",
        "Que foge; que evita o compromisso.",
        "Que pode ser dobrado sem quebrar; maleável.",
        "Que age com generosidade; que é bondoso e desprendido.",
        "Que tem o hábito de se levantar cedo.",
        "Que muda frequentemente de ideias; inconstante.",
        "Que tem felicidade; contente, alegre."
    ])
    const lista2 = ([
       " Que age movido por impulsos; precipitado.",
"Que não consegue ficar quieto; inquieto.",
"Que se irrita facilmente; colérico.",
"Que está em atividade; dinâmico.",
"Que se excita facilmente; suscetível a excitações.",
"Que tem a cor da pele avermelhada; ruborizado.",
"Que age com agressividade; combativo.",
"Que exerce liderança; guia ou comanda um grupo.",
"Que consegue convencer; persuasivo.",
"Que tem grande vitalidade; enérgico.",
"Que se volta para fora; sociável.",
"Que é agitado; tumultuado.",
"Que não tem paciência; ansioso.",
"Que se dedica a empreendimentos; que busca inovações.",
"Que é o primeiro a realizar algo; inovador.",
"Que faz muito barulho; ruidoso.",
"Que se orienta pela prática; funcional.",
"Que tem caráter teatral; exagerado.",
"Que costuma esquecer - se; distrativo.",
"Que pratica esportes; atlético.",
"Que tem espírito de competição; que gosta de competir.",
"Que suporta pressões e adversidades; robusto.",
"Que tende a dominar; autoritário.",
"Que não tolera diferenças; inflexível.",
"Que é teimoso; persistente.",
"Que se irrita facilmente; colérico.",
"Que é corajoso e arrojado; destemido.",
    ])
    const lista3 = ([
        "Que tende a ver as coisas pelo lado negativo; descrente.",
        "Que está imerso em melancolia; triste, nostálgico.",
       " Que está ressentido; de mau humor.",
       " Que age com moderação; moderado.",
       " Que está agitado; ansioso.",
       " Que está afastado; reservado.",
       " Que está em silêncio; calmo.",
       " Que guarda para si; discreto.",
       " Que aceita resignadamente as situações; conformado.",
        "Que está com sensação de tristeza; melancólico.",
       " Que perdeu o ânimo; desmotivado.",
       " Que está absorto em pensamentos; reflexivo.",
       " Que se volta para dentro de si mesmo; reflexivo.",
       " Que age movido pelo interesse próprio; individualista.",
       " Que estabelece exigências; rigoroso.",
       " Que é sensível às influências; vulnerável.",
       " Que gosta de ler; apreciador da leitura.",
       " Que se move devagar; vagaroso.",
       " Que está com aparência triste; entristecido.",
       " Que é calado; silencioso.",
       " Que se dedica ao intelecto; voltado para o pensamento.",
       " Que tem uma memória eficiente; lembrador.",
       " Que observa com atenção; atento.",
       " Que não é grato; desagradecido.",
      "  Que não está satisfeito; descontente.",
      "  Que age com abnegação; altruísta.",
      "  Que não pode ser consolado; extremamente triste.",
    ])
    const lista4 = ([
       " Que age com cuidado; atento.",
      "  Que segue um método; organizado.",
      "  Que permanece constante; equilibrado.",
      "  Que aceita sem reagir; submisso.",
      "  Que é tranquilo; sereno.",
      "  Que está absorto em pensamentos; reflexivo.",
      "  Que está em paz; sereno.",
      "  Que é mantido sob controle; moderado.",
      "  Que tem folga; desocupado.",
      "  Que é sereno; tranquilo.",
      "  Que não tem urgência; tranquilo.",
      "  Que se move devagar; vagaroso.",
      "  Que não tem piedade; inexorável.",
       " Que age com comedimento; moderado.",
       " Que está em paz; sereno.",
       " Que está voltado para dentro de si mesmo; introspectivo.",
       " Que guarda para si; discreto.",
       " Que é propenso a sonhar; imaginativo.",
       " Que prefere seguir uma rotina; metódico.",
       " Que demora para assimilar novos conhecimentos.",
       " Que persevera; persistente.",
       " Que é teimoso; persistente.",
      "  Que tem timidez; reservado.",
       " Que permanece inalterado; consistente.",
       " Que age com sensatez; prudente.",
       " Que não demonstra interesse; apático.",
       " Que está sem energia; sem ânimo.",
    ])

    return {
        Lista1: lista1,
        Lista2: lista2,
        Lista3: lista3,
        Lista4: lista4
    }
};